### ISSUE TITLE
Compile error for master branch (undefined function: SET-POSTPROCESSING-FN)

### ISSUE THREAD

**Issue by chunqishi** [charlieg/Sparser#1]
# Both clozure and allegro give same error.

<<clozure cl>>
$> ccl -l Sparser/load-nlp.lisp

> Error: Undefined function SET-POSTPROCESSING-FN called with arguments (#<TYPE BUNDLE-TYPE> #<Compiled-function |postprocess-BUNDLE-TYPE| #x302000F17BFF>) .
> While executing: (:INTERNAL CCL::PROGN-IN-ENV CCL::CHEAP-EVAL-IN-ENVIRONMENT), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry applying SET-POSTPROCESSING-FN to (#<TYPE BUNDLE-TYPE> #<Compiled-function |postprocess-BUNDLE-TYPE| #x302000F17BFF>).
> Type :? for other options.
> 1 >
> ---
> 
> <<allegro cl>>
> ; While EVALUATING an unknown function in
> # P"~/Sparser/Mumble/objects/postprocess-objects.lisp":
> 
> Error: attempt to call `SET-POSTPROCESSING-FN' which is an undefined
>        function.
> #   [condition type: UNDEFINED-FUNCTION]

**Comment by charlieg** [comment]
Sorry @chunqishi this project is no longer actively maintained. I personally haven't had a working copy of it in years.

**Comment by ddmcdonald** [comment]
In general there are a fair number of locally undefined functions and other compiler warnings that will turn up in the process of loading, we're making so many commits each day that we can't always keep up with inadvertently introducing warnings, and referring to functions that are defined in a module that has not yet been loaded.

This one is completely bizarre though, and suggests that something is off in what you're loading since none of the rest of us are getting it.

-- David

p.s. Charlie, how is it that you're still listed here? It ought to be one of us who's actually getting paid to do this work!

> On Jul 10, 2015, at 1:17 AM, chunqishi notifications@github.com wrote:
> 
> Both clozure and allegro give same error.
> 
> <>
> $> ccl -l Sparser/load-nlp.lisp
> 
> Error: Undefined function SET-POSTPROCESSING-FN called with arguments (# #) .
> While executing: (:INTERNAL CCL::PROGN-IN-ENV CCL::CHEAP-EVAL-IN-ENVIRONMENT), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry applying SET-POSTPROCESSING-FN to (# #).
> Type :? for other options.
> 1 >
> 
> <>
> ; While EVALUATING an unknown function in
> #P"~/Sparser/Mumble/objects/postprocess-objects.lisp":
> Error: attempt to call `SET-POSTPROCESSING-FN' which is an undefined
> function.
> 
> [condition type: UNDEFINED-FUNCTION]
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/charlieg/Sparser/issues/1.

David McDonald, Phd     781.718.1964 (cell)  
davidmcdonald@alum.mit.edu
http://alum.mit.edu/www/davidmcdonald/
